# Generated by Django 5.0.5 on 2024-05-11 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
        ('center', '0001_initial'),
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine'),
        ),
        migrations.AddField(
            model_name='slot',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign'),
        ),
    ]
