# Generated by Django 5.0.5 on 2024-05-27 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 11, 30, 14, 240642, tzinfo=datetime.timezone.utc)),
        ),
    ]
